
# Builds and deploys Docker image to Docker hub when a new tag/release is created

name: Builds and publishes new Docker images to Docker hub when a new tag is created
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get tag version number
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Replace API URL
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "https://dev-api.aista.com"
        replace: "https://api.aista.com"
        regex: false
    - name: Replace API URL
      uses: jacobtomlinson/gha-find-replace@v2
      with:
        find: "https://dev-hub.aista.com"
        replace: "https://hub.aista.com"
        regex: false
    - name: Build and push Docker CI images backend/frontend
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker build -t aistamagic/hub:${{ steps.get_version.outputs.VERSION }} -f ./Dockerfile .
        docker push aistamagic/hub:${{ steps.get_version.outputs.VERSION }}
